<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMedEDYR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMedEDYR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMedEDYR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMedEDYR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMedEDYR\App_KernelDevDebugContainer([
    'container.build_hash' => 'MedEDYR',
    'container.build_id' => '8e44b2a7',
    'container.build_time' => 1607717276,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMedEDYR');
